name: Fetch Community Feeds

on:
  schedule:
    - cron: '0 * * * *'   # run hourly
  workflow_dispatch:      # manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: assets/js

      - name: Fetch LinkedIn Feed
        env:
          CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        run: node fetchLinkedIn.js > ../_data/linkedin.json
        working-directory: scripts

      - name: Fetch Reddit Feed
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          ACCESS_TOKEN: ${{ secrets.REDDIT_ACCESS_TOKEN }}
          SUBREDDIT: 'YourSagaSubreddit'
        run: node fetchReddit.js > ../_data/reddit.json
        working-directory: scripts

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add _data/linkedin.json _data/reddit.json
          git diff --cached --exit-code || git commit -m "Update community feeds"
          git push
