name: Fetch Community Feeds
on:
  schedule: [{ cron: '0 * * * *' }]
  workflow_dispatch:

defaults:
  run:
    working-directory: ${{ vars.WORKDIR }}

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache NPM modules
        uses: actions/cache@v3
        with:
          path: ${{ vars.WORKDIR }}/node_modules
          key:  ${{ runner.os }}-node-${{ hashFiles(vars.WORKDIR + '/package-lock.json') }}

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - name: Install dependencies
        run: npm ci

      - name: Fetch LinkedIn Feed
        env:
          CLIENT_ID:               ${{ secrets.LINKEDIN_CLIENT_ID }}
          CLIENT_SECRET:           ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          LINKEDIN_REFRESH_TOKEN:  ${{ secrets.LINKEDIN_REFRESH_TOKEN }}
        run: |
          node ${{ vars.LINKEDIN_JS }} \
            > ../${{ vars.DATA_DIR }}/linkedin.json

      - name: Fetch Reddit Feed
        env:
          CLIENT_ID:             ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET:         ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_REFRESH_TOKEN:  ${{ secrets.REDDIT_REFRESH_TOKEN }}
          SUBREDDIT:             ${{ vars.SUBREDDIT }}
        run: |
          node ${{ vars.REDDIT_JS }} \
            > ../${{ vars.DATA_DIR }}/reddit.json

      - name: Commit updated data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "actions@github.com"
          git add ${{ vars.DATA_DIR }}/linkedin.json ${{ vars.DATA_DIR }}/reddit.json
          git diff --quiet --cached || git commit -m "Update community feeds"
          git push
